WITH SALES_DATA AS (select salesemployeeid, saledate, saleamount, QUOTA, 
SUM(SALEAMOUNT) OVER(PARTITION BY SALESEMPLOYEEID ORDER BY SALEDATE) as RUNNING_TOTAL
from employees join sales 
on employees.EMPLOYEEID = sales.SALESEMPLOYEEID
ORDER BY SALESEMPLOYEEID)

SELECT salesemployeeid, saledate, saleamount, RUNNING_TOTAL , CAST(RUNNING_TOTAL AS FLOAT) / QUOTA AS PERCENT_QUOTA FROM SALES_DATA
